version: '3.3'


services:
# Kafka
  kafka:
    build: 
      context: kafka-adapter/
      args:
        - LIBRDKAFKA_VERSION=$LIBRDKAFKA_VERSION
        - CONFLUENT_KAFKA_VERSION=$CONFLUENT_KAFKA_VERSION
    ports:
      - "3030:3030"
    env_file: 
      - .env
    networks:
      - db-adapter
    external_links:
      - elasticsearch:elasticsearch
    depends_on:
      - redis
    entrypoint:
      - python
      - /home/src/db-adapter.py
    restart: always

# Redis Webservice
  redis:
    build: redis/
    sysctls:
      - net.core.somaxconn=65535
    networks:
      - db-adapter
    restart: always

# Network
networks:
  db-adapter:



