version: '3.3'


services:
# Kafka
  kafka:
    build: kafka-logstash-adapter/
    ports:
      - "3030:3030"
    environment:
      # seperate kafka entries with ","
      - KAFKA_TOPICS=SensorData
      - BOOTSTRAP_SERVERS=il061,il062
      - KAFKA_GROUP_ID=db-adapter
      - enable_kafka_adapter=false
      - enable_sensorthings=false
    networks:
      - elk_datastore
    external_links:
      - elasticsearch:elasticsearch
    depends_on:
      - redis
    entrypoint:
      - python
      - /home/code/kafka-adapter.py
    restart: always


# Redis Webservice
  redis:
    build: redis/
    sysctls:
      - net.core.somaxconn=65535
    networks:
      - elk_datastore
    restart: always

# Network
networks:
  elk_datastore:
    external: true


