version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - ../esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx6g -Xms6g"
    healthcheck:
      test: "exit 0"
      interval: 1m00s
      timeout: 10s
      retries: 3
    networks:
      - datastore



  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - datastore
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - datastore
    depends_on:
      - elasticsearch



  grafana:
    image: grafana/grafana:5.0.2
    ports:
      - 3001:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - datastore
    depends_on:
      - elasticsearch
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
#      ELASTICSEARCH_USER: ${ES_USERNAME}
#      ELASTICSEARCH_PASSWORD: ${ES_PASSWORD}



# https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook
  jupyter:
    image: 127.0.0.1:5001/jupyter
    build: jupyter/
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/work:/home/jovyan/work
    networks:
      - datastore


networks:
  datastore:


