version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx8g -Xms8g"
    healthcheck:
      test: "exit 0"
      interval: 1m00s
      timeout: 10s
      retries: 3
    networks:
      - datastore
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 10G
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    configs:
      - source: esconfig
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: eslog4jconf
        target: /usr/share/elasticsearch/config/log4j2.properties

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.0.1
    configs:
      - source: lsconfig
        target: /usr/share/logstash/config/logstash.yml
      - source: lspipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - datastore
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 3
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.1
    configs:
      - source: kibanaconfig
        target: /usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - datastore
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
      replicas: 2
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
       condition: on-failure

volumes:
  esdata:
    driver: local
  pipeline:
    driver: local

networks:
  datastore:

configs:
  esconfig:
    file: elasticsearch/config/elasticsearch.yml
  eslog4jconf:
    file: elasticsearch/config/log4j2.properties
  kibanaconfig:
    file: kibana/config/kibana.yml
  lsconfig:
    file: logstash/config/logstash.yml
  lspipeline:
    file: logstash/pipeline/logstash.conf
